// Generated by CoffeeScript 1.9.1
var component, dom, inject, ref, svg;

ref = require('odojs'), component = ref.component, dom = ref.dom, svg = ref.svg;

inject = require('injectinto');

inject.bind('page:error', component({
  render: function(state, params) {
    var titileattr;
    titileattr = {
      attributes: {
        "class": 'title'
      },
      style: {
        width: '100%'
      }
    };
    return dom('div', {
      attributes: {
        "class": 'wrapper error'
      }
    }, [
      dom('div', [
        svg('svg', {
          attributes: {
            "class": 'logo'
          }
        }, [
          svg('use', {
            'xlink:href': "/odojs-examples-1.0.0.min.svg#odojs"
          })
        ]), dom('div', [dom('p', params.page.message), dom('p', params.page.details)])
      ])
    ]);
  }
}));
