// Generated by CoffeeScript 1.9.1
var body, component, exe, loading, odoql, ref, relay, root, router, scene, widget;

ref = require('odojs'), component = ref.component, widget = ref.widget;

odoql = require('odoql/odojs');

component.use(odoql);

widget.use(odoql);

require('./default');

require('./errors');

router = require('./router');

root = document.querySelector('#root');

body = document.querySelector('body');

loading = document.querySelector('#loading');

body.removeChild(loading);

exe = require('odoql-exe');

exe = exe();

relay = require('odo-relay');

scene = relay(root, router, exe, {
  queries: window.__queries,
  state: window.__state
});

module.exports = scene;
