// Generated by CoffeeScript 1.9.1
var body, component, exe, fn, i, len, loading, odoql, page, ref, ref1, relay, root, route, router, scene, widget;

ref = require('odojs'), component = ref.component, widget = ref.widget;

odoql = require('odoql/odojs');

component.use(odoql);

widget.use(odoql);

require('../shared/');

router = require('./router');

root = document.querySelector('#root');

body = document.querySelector('body');

loading = document.querySelector('#loading');

body.removeChild(loading);

exe = require('odoql-exe');

exe = exe();

relay = require('odo-relay');

scene = relay(root, router, exe, {
  queries: window.__queries,
  state: window.__state
});

route = require('odo-route');

page = require('page');

ref1 = route.routes();
fn = function(route) {
  return page(route.pattern, function(e) {
    return scene.update(route.cb({
      url: e.pathname,
      params: e.params
    }));
  });
};
for (i = 0, len = ref1.length; i < len; i++) {
  route = ref1[i];
  fn(route);
}

module.exports = scene;
