// Generated by CoffeeScript 1.9.1
var app, bodyParser, build, component, compression, exe, express, minirelay, odoql, oneDay, path, port, ref, split, stringify, widget;

path = require('path');

express = require('express');

app = express();

compression = require('compression');

app.use(compression());

bodyParser = require('body-parser');

app.use(bodyParser.urlencoded({
  extended: true
}));

app.use(bodyParser.json());

oneDay = 1000 * 60 * 60 * 24;

app.use('/dist', express["static"](path.join(__dirname, 'dist'), {
  maxAge: oneDay
}));

app.use('/public', express["static"](path.join(__dirname, 'public'), {
  maxAge: oneDay
}));

ref = require('odojs'), component = ref.component, widget = ref.widget;

odoql = require('odoql/odojs');

component.use(odoql);

widget.use(odoql);

stringify = require('odojs/stringify');

component.use(stringify);

split = require('odoql-exe/split');

build = require('odoql-exe/buildqueries');

exe = require('odoql-exe');

exe = exe();

minirelay = function(component, params, cb) {
  var queries, run;
  queries = component.query(params);
  queries = split(exe, queries);
  queries = queries.local;
  run = build(exe, queries);
  return run(function(err, state) {
    var html;
    if (err != null) {
      return cb(err);
    }
    html = component(state, params);
    return cb(null, {
      params: params,
      queries: queries,
      state: state,
      html: html
    });
  });
};

app.get('/*', function(req, res) {
  component = require('./app/default');
  return minirelay(component, {}, function(err, result) {
    return res.send("<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset=\"utf-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge, chrome=1\" />\n    <meta name=\"viewport\" content=\"width=700\">\n    <title>Odo.js Examples</title>\n    <link rel=\"stylesheet\" href=\"/public/loading.css\" />\n    <link rel=\"stylesheet\" href=\"/dist/odojs-examples-1.0.0.min.css\" />\n  </head>\n  <body>\n    <div class=\"loading wrapper\">\n      <svg class=\"logo\">\n        <use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"/dist/odojs-examples-1.0.0.min.svg#odojs\"></use>\n      </svg>\n      <div class=\"timeout\" style=\"display: none;\">\n        <h1>LOADING TOO SLOW<br/>SOMETHING IS WRONG</h1>\n      </div>\n    </div>\n    <script src=\"/public/loading.js\"></script>\n    <script>\n      window.__queries = " + (JSON.stringify(result.queries)) + ";\n      window.__state = " + (JSON.stringify(result.state)) + ";\n    </script>\n    <script src=\"/dist/odojs-examples-1.0.0.min.js\"></script>\n  </body>\n</html>");
  });
});

port = 8085;

app.listen(port);

console.log("Odo.js examples are listening on port " + port + "...");
