// Generated by CoffeeScript 1.9.1
var app, async, bodyParser, compression, express, fs, oneDay, path, port, ql;

express = require('express');

compression = require('compression');

bodyParser = require('body-parser');

path = require('path');

ql = require('odoql');

async = require('odo-async');

fs = require('fs');

app = express();

app.use(compression());

app.use(bodyParser.urlencoded({
  extended: true
}));

app.use(bodyParser.json());

oneDay = 1000 * 60 * 60 * 24;

app.use(express["static"](__dirname, {
  maxAge: oneDay
}));

app.get('/*', function(req, res) {
  return res.sendFile(path.join(__dirname, 'index.html'));
});

port = 8085;

app.listen(port);

console.log("Odo.js examples are listening on port " + port + "...");
