// Generated by CoffeeScript 1.9.1
var app, bodyParser, component, compression, exe, express, hook, odoql, oneDay, oneshot, path, port, ref, route, router, stringify, widget;

express = require('express');

app = express();

compression = require('compression');

app.use(compression());

bodyParser = require('body-parser');

app.use(bodyParser.urlencoded({
  extended: true
}));

app.use(bodyParser.json());

oneDay = 1000 * 60 * 60 * 24;

path = require('path');

app.use('/dist', express["static"](path.join(__dirname, 'dist'), {
  maxAge: oneDay
}));

oneshot = require('odo-relay/oneshot');

ref = require('odojs'), component = ref.component, widget = ref.widget, hook = ref.hook;

odoql = require('odoql/odojs');

component.use(odoql);

widget.use(odoql);

hook.use(odoql);

stringify = require('odojs/stringify');

component.use(odoql);

exe = require('odoql-exe');

exe = exe();

require('./shared/');

router = require('./shared/router');

route = require('odo-route');

app.get('/favicon.ico', function(req, res) {
  return res.status(404).end();
});

app.get('/*', function(req, res) {
  var params;
  params = route(req.url);
  return oneshot(exe, router, params, function(err, result) {
    return res.send("<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset=\"utf-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge, chrome=1\" />\n    <meta name=\"viewport\" content=\"width=700\">\n    <title>Odo.js Examples</title>\n    <link rel=\"stylesheet\" href=\"/dist/odojs-examples-1.0.0.min.css\" />\n  </head>\n  <body>\n    <div id=\"loading\" class=\"wrapper\" style=\"display: none;\">\n      <p>Loading too slow, something is wrong</p>\n    </div>\n    <script src=\"/dist/loading.js\"></script>\n    <script>\n      window.__queries = " + (JSON.stringify(result.queries)) + ";\n      window.__state = " + (JSON.stringify(result.state)) + ";\n    </script>\n    " + result.html + "\n    <script src=\"/dist/odojs-examples-1.0.0.min.js\"></script>\n  </body>\n</html>");
  });
});

port = 8085;

app.listen(port);

console.log("Odo.js examples are listening on port " + port + "...");
