// Generated by CoffeeScript 1.9.1
var component, dom, ql, ref, svg;

ref = require('odojs'), component = ref.component, dom = ref.dom, svg = ref.svg;

ql = require('odoql');

module.exports = component({
  query: function(params) {
    return {
      test: ql.concat('Hel', 'lo')
    };
  },
  render: function(state, params) {
    return dom('div', {
      attributes: {
        "class": 'wrapper'
      }
    }, [
      svg('svg', {
        attributes: {
          "class": 'logo'
        }
      }, [
        svg('use', {
          'xlink:href': "/dist/odojs-examples-1.0.0.min.svg#odojs"
        })
      ]), dom('div', state.test)
    ]);
  }
});
