// Generated by CoffeeScript 1.9.1
var component, dom, inject, ref, svg;

ref = require('odojs'), component = ref.component, dom = ref.dom, svg = ref.svg;

inject = require('injectinto');

inject.bind('page:error', component({
  render: function(state, params) {
    var titileattr;
    titileattr = {
      attributes: {
        "class": 'title'
      },
      style: {
        width: '100%'
      }
    };
    return dom('div', {
      attributes: {
        "class": 'wrapper error grid grid--center'
      }
    }, [
      dom('div', [
        dom('div', {
          attributes: {
            "class": 'logo'
          }
        }, [
          svg('svg', titileattr, [
            svg('use', {
              'xlink:href': "/dist/wedding-1.0.0.min.svg#emblem"
            })
          ])
        ]), dom('div', [dom('h1', params.page.message), dom('p', params.page.details)])
      ])
    ]);
  }
}));
