// Generated by CoffeeScript 1.9.1
var cycle, path, state;

cycle = function(cb) {
  var handle, prev, step;
  prev = null;
  handle = null;
  step = function(t) {
    var dt;
    if (prev === null) {
      prev = t;
      return handle = window.requestAnimationFrame(step);
    }
    dt = t - prev;
    prev = t;
    cb(dt);
    return handle = window.requestAnimationFrame(step);
  };
  handle = window.requestAnimationFrame(step);
  return {
    fin: function() {
      window.cancelAnimationFrame(handle);
      window.__loadinghandle = null;
      return document.querySelector('.loading').remove();
    }
  };
};

path = document.querySelector('.loading path');

state = 0;

window.__loadinghandle = cycle(function(dt) {
  return state += dt / 500;
});

setTimeout((function() {
  var timeout;
  if (window.__loadinghandle == null) {
    return;
  }
  timeout = document.querySelector('.loading .timeout');
  return timeout.style.display = 'block';
}), 10000);
