// Generated by CoffeeScript 1.9.1
var Router, body, component, exe, odoql, ref, relay, scene, widget;

ref = require('odojs'), component = ref.component, widget = ref.widget;

odoql = require('odoql/odojs');

relay = require('odo-relay');

component.use(odoql);

widget.use(odoql);

require('./default');

require('./errors');

Router = require('./router');

body = document.querySelector('body');

exe = require('odoql-exe');

exe = exe();

scene = relay(body, Router, exe);

module.exports = scene;
