// Generated by CoffeeScript 1.9.1
var component, dom, inject, ql, ref, svg;

ref = require('odojs'), component = ref.component, dom = ref.dom, svg = ref.svg;

inject = require('injectinto');

ql = require('odoql');

inject.bind('page:default', component({
  query: function(params) {
    return {
      test: ql.concat('Hel', ql["if"](ql.gt(6, 5), 'lo World', 'lo'))
    };
  },
  render: function(state, params) {
    return dom('div', {
      attributes: {
        "class": 'wrapper'
      }
    }, [
      svg('svg', {
        attributes: {
          "class": 'logo'
        }
      }, [
        svg('use', {
          'xlink:href': "/dist/odojs-examples-1.0.0.min.svg#odojs"
        })
      ]), dom('div', state.test)
    ]);
  }
}));
