// Generated by CoffeeScript 1.9.1

/*
Map url patterns to parameters
 */
var route;

route = require('odo-route');

route('/', function() {
  return {
    page: {
      name: 'default'
    }
  };
});

route('*', function(p) {
  return {
    status: 404,
    page: {
      name: 'error',
      message: "Sorry, the \"" + p.url + "\" page was not found."
    }
  };
});

module.exports = route;
